### ISSUE TITLE
Add mapster to new image and imagemap

### ISSUE THREAD

**Issue by yoeril** [jamietre/ImageMapster#112]
Hi,

I am using your ImageMapster JQuery plugin and finding it quite usefull!

I use it for my scout group so people can easily see what parts need to be on their uniform by hovering over it. A "rotated" version of the picture can be seen by going to the next picture (hover over the arrow on the image or use the arrow-keys of your keyboard), so I need to change the src and usemap attributes of the image.

This is where things go wrong. If I change the usemap attribute of an image, ImageMapster doesn't seem to work on a different image than the first one.
If I go back to the first image it works again. So it seems it keeps being bound on the original image, although I do use the "unbind" functionality.

Here's the main JS code, which gets called everytime the image needs to change:

function showPicture(){
    $('#test').mapster('unbind');

```
index = (index + 11)%11;
$("#test").attr("usemap", "#imgmap"+index)
$("#test").attr("src", "Kameleon-"+index+".jpg?" + new Date().getTime());

$('#test').mapster({
    mapKey: 'data-key',
    fillColor: 'ff0000',
    fillOpacity: 0.3,
    onMouseover: function (e){
        $("body").append("<p id='preview' align=center><img src='"+info[e.key]["img"]+"' alt='Uniform (J)VG-leiding' />"+
"<br /><span style=\"background-color: white;\">"+info[e.key]["tekst"]+"</span></p>");
        $("#preview")
            .css("top",(e.e.pageY + 5) + "px")
            .css("left",(e.e.pageX + 5) + "px")
            .fadeIn("fast");
    },
    onMouseout: function (e){
        $("#preview").remove();
    }
});
```

}

Here's how it works without changing the usemap: http://dezwaluw.org/test/test4.html
And here how it doesn't work with changing the usemap: http://dezwaluw.org/test/test5.html

Thanks in advance!

**Comment by VovaChop** [comment]
Hello.

Try just create new instance of ImageMapster after changing image at element.
I made this with all options from previous image. It helped solve my same problem)

$('#your-image-id').mapster(someYourOptions);

**Comment by techfg** [comment]
Hello @yoeril -

Thank you for the inquiry, sorry for the delayed reply!

Unfortunately, the URLs you provided no longer work so its difficult to say what the issue you were having was.  There were some issues with 'unbind/rebind' in prior versions of IM so its possible you were encountering one of those.  All the known issues have been addressed in the latest version.

What you are trying to achieve should work although there may be other issues still lurking.  If this is still a problem for you, if you could update this issue per our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines, we'd be happy to investigate further.

**Comment by techfg** [comment]
Hello @yoeril -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.
