### ISSUE TITLE
Change area color on click

### ISSUE THREAD

**Issue by chirag-khatsuriya** [jamietre/ImageMapster#115]
Hi I want to change background color of area when I click on it. i.e I have 3 status each status has different color, as per selected status by user, the color of area should be change on click. 

any one can help me?

**Comment by techfg** [comment]
Hello @chirag-khatsuriya -

Were you able to utilize the approach that @jamietre provided using the `set` API to resolve this?

**Comment by techfg** [comment]
Hello @chirag-khatsuriya -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.
