### ISSUE TITLE
Multiple images map working, just need ImageMapster to make it iphone compatible

### ISSUE THREAD

**Issue by danielocdh** [jamietre/ImageMapster#134]
I have a map that needs to be divided in multiple images, everything is working fine. 

Is it possible to use ImageMapster to make it iphone compatible?

What would be the steps with the minimum amount of change to the current multiple images/areas map.

Thank you.

**Comment by techfg** [comment]
Hello @danielocdh -

Thank you for your inquiry, apologies for the delayed reply.

ImageMapster does support iPhone, even back at the time when you originally asked this question and there are not any "extra" steps required.  You don't indicate whether or not IM wasn't working for you on iPhone or if you were just asking a general question so I'm going to close out this issue since it addresses the question you posed.

If you have any further questions, please see our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page for options on general usage/how to questions.  If you believe you've identified a potential bug, please open a new issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
