### ISSUE TITLE
Imagemapster throws error when included with requirejs

### ISSUE THREAD

**Issue by at0g** [jamietre/ImageMapster#136]
I can't import the imagemapster library with requirejs. Simply including the library throws the following error:

_Uncaught TypeError: Cannot read property 'defer' of undefined_

There's a js fiddle here showing the problem. http://jsfiddle.net/gjy2N/

**Comment by froginvasion** [comment]
I just removed define support completely. I just shim this one then, and make sure jquery is loaded in the shim. For those interested, i changed on line 812 to

    (function (factory) {
        jQuery.mapster_when = factory();
	});

This renders it unusable for node I suppose though. I don't use node but you could try to see if it works if you change it to

    (function (factory) {
        if (typeof module.exports !== "undefined") {
            module.exports = factory();
        } else {
             jQuery.mapster_when = factory();
       }
	});

This resembles the previous version of that wrapper, but just ignores AMD

I'd suggest you remove AMD support for now, so that at least it doesn't crash with AMD when used. People just have to know that they need to shim it.

**Comment by hannwong** [comment]
@froginvasion For enabling it to load with RequireJS, I just skipped the blank "define" scenario. ::

    })(typeof define == 'function' && false
        ? define
 
I haven't tried it with r.js, though. Will try your suggestion. Thanks!

**Comment by Jamdadesuhas** [comment]
Hi,

I have the issue "Cannot read property 'defer' of undefined".
I am using it in Outsystems Mobile I get this error. In outsystems web it works fine. but in outsystems mobile it gives me error.

**Comment by jamietre** [comment]
Bearing in mind that ImageMapster hasn't been maintained in years, this is probably because you're using a mobile version of jQuery that doesn't implement `$.defer`

**Comment by uimarkup** [comment]
I’m having the same issue with imagemapster, does imagemapster support RequireJS with AMD modules?

**Comment by techfg** [comment]
As of v1.3.0, ImageMapster now has full UMD support and is available via NPM at [imagemapster](https://www.npmjs.com/package/imagemapster).
