### ISSUE TITLE
area href empty or not specified

### ISSUE THREAD

**Issue by ShadoW69** [jamietre/ImageMapster#137]
if href isn't set or empty in area tag the hover highlight isn't working, you can select it but not hover over it...
http://jsfiddle.net/sb9j7/2767/

**Comment by techfg** [comment]
Hello @ShadoW69 -

Thank you for reporting this, apologies for the delayed reply!

As @jamietre indicates, this is a bug but there are two different scenarios in-play here:

1. `href` is not set/specified - In this scenario, per the HTML spec, IM should treat this as the equivalent of `nohref` being specified.  In your fiddle, the `carrots` area did not specify either an `href` or `nohref` attribute so IM should treat this as `nohref` which it does and, as expected, disables highlight/select/etc.
2. 'href` is specified but is empty - In this scenario, per the HTML spec, the empty value is valid so IM does not disable functionality.  This is where the bug is - the area should highlight but it currently does not.  The fact that it can be selected in this case is expected behavior.

The issue with an area with an empty href not highlighting will be addressed in v1.5.2.
