### ISSUE TITLE
Docs incorrectly state that highlighting will be disabled when staticState option is specified

### ISSUE THREAD

**Issue by ZetIsDeadBaby** [jamietre/ImageMapster#138]
According to docs `staticState: false` should prevents area from being highlighted or selected. See WA on your [USA demo](http://www.outsharked.com/imagemapster/examples/usa.html) map, area is still highlighted.

`staticState: false` + `highlight: false` will do the trick, but area is still clickable if `clickNavigate: true`.

**Comment by techfg** [comment]
@ZetIsDeadBaby -

Thank you for pointing this out and apologies for the delayed reply.

As @jamietre indicates, `staticState` is intended to only affect `selected` state and not affect highlighting in any way.  As you point out, the demo page docs indicate otherwise and there are also a couple of points on the main docs page that infer highlighting will be affected as well.

Marking this as a docs bug and will address when docs are updated.

Relevant docs that require adjusting:
1. [Big USA Map Demo](http://www.outsharked.com/imagemapster/default.aspx?demos.html) - Highlighting will still occur
> staticState=false which prevents it from being _**highlighted**_ or selected

2. [Docs](http://www.outsharked.com/imagemapster/default.aspx?docs.html)
    1. staticState description - staticState still maintains other interactive features (e.g. highlight, click, etc.)
        > When true or false, the map or area to which this option applies will be permanently selected or deselected. **_Typically this is more useful applied to individual areas that you want to exclude from the interactive part of the map._**
    2. mapKey description - Not functionally identical since highlight would still work as would click, etc.
        > When mapKey is present, any area tags that are missing this attribute will be excluded from the image map entirely. **_This is functionally identical to setting staticState=false for these areas_**, except they will be inaccessible through the API.
    3. isMask description - highlighting will still occur when staticState is set
        > Normally, every area in an imagemap is an active area, and would be highlighted when moused over (**_unless its behavior was otherwise specified with staticState_**).
