### ISSUE TITLE
Can Excanvas or fxCanvas fix the IE compatibility with HTML5 Canvas?

### ISSUE THREAD

**Issue by hatchmedia** [jamietre/ImageMapster#149]
Hi,

I implemented imagemapster and everything works perfect apart from the altimage not displaying the image but a black solid colour with transparency.

I know this is a known issue but can these be rectified with conditional use of excanvas or fxcanvas to add canvas support to later IEs?

thanks

**Comment by techfg** [comment]
Hello @hatchmedia -

Thank you for your inquiry and apologies for the delay in circling back on this.

Please let us know if you are still seeking a solution for this and if so, please try the latest version of IM and update this issue per our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines so that we can investigate further.

**Comment by techfg** [comment]
Hello @hatchmedia -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.
