### ISSUE TITLE
Ploy position is incorrect in Safari if set style="width:80%" for the image

### ISSUE THREAD

**Issue by xiuxiu** [jamietre/ImageMapster#156]
Here is my image code. The ploy is incorrect in latest Safari. But works fine in Firefox and Chrome.

&lt;img class="map" src="main-page-v5.jpg" usemap="#simple" style="width:80%;height:80%"&gt;

When I remove style="width:80%;height:80%", it works fine in Safari, too.

**Comment by techfg** [comment]
Hello @xiuxiu -

Thank you for the inquiry, apologize for the delayed reply.

If this is still an issue for you, please update this issue per our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines and we'd be happy to investigate further.  Without a full repro and specifics on which Safari version this was/is a problem with, there is not much we can do at this time.

**Comment by techfg** [comment]
Hello @xiuxiu -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.
