### ISSUE TITLE
imagemapster different areas with different colors

### ISSUE THREAD

**Issue by rapha2** [jamietre/ImageMapster#159]
I was wondering if the following is possible with imagemapster: i need area 1 and area 2.
When i hover one of them both have to highlight but in different colors, for example area 1 is blue and green when i hover one of them and area 2 is yellow and red on hover.

This is what i tried so far:

```
 <script type="text/javascript">
    $(document).ready(function ()
    {
    $('#Landkarte').mapster({
    fillOpacity:0.5,
    mapKey: 'data-group',
    areas : [
    {key : 'keyone',fillColor: 'FF0000',fillOpacity : 0.5},
    {key : 'keytwo',fillColor: 'FFFF00',fillOpacity : 0.5}, 
    });
    });
 </script>
```

And my HTML

```
   <area data-group="keyone,keytwo" href="#" coords="117,65,370,89" shape="rect"></area>
   <area data-group="keyone" href="#" coords="117,65,370,89" shape="rect"></area>
```

This obviously doesn't really work the way I want. I would be very greatful if someone could help me out!

Best regards,

Raph

**Comment by techfg** [comment]
Hello @rapha2 -

I'm going to go ahead and close this issue since we haven't heard back from you.  If you would like to propose a new feature, please feel free to open a new feature request with a clear description of what you are trying to accomplish and we'd be happy to review/consider.

Thank you!
