### ISSUE TITLE
Tooltips/Highlight/Select incorrect when AREA `shape` attribute is missing or its value is non-conforming/empty

### ISSUE THREAD

**Issue by RWAP** [jamietre/ImageMapster#170]
For some reason, if you have ModPagespeed enabled, with the elide_attributes filter enabled, this impacts on ImageMapster.

I have a site which uses two images to show a highlighted area onclick or on mouseover.

This works fine under ImageMapster.

However, if elide_attributes is enabled - the highlighted area is not shown in Google Chrome or FIrefox (IE10 still shows it successfully).

See https://developers.google.com/speed/pagespeed/module/filter-attribute-elide

Even more oddly - it seemed to work after a while on Firefox when using 2 GIF images, but not when using two PNG images.

No errors are shown in Firebug, so it is difficult to guess which stripped attribute is causing the problem!

**Comment by techfg** [comment]
@RWAP -

Thank you for reporting this, apologies for the delayed reply!

You're analysis is correct - there is a bug in IM that does not account for shape attributes that have non-confirming/missing values.  In your situation, since elide_attributes is "removing" the `shape="rect"` because its the default, when IM parses the HTML, it should apply `rect` as the default shape since its missing according to the [AREA element spec](https://html.spec.whatwg.org/multipage/image-maps.html#the-area-element).

There are actually a few places where IM doesn't currently account for missing/non-confirming values so I've adjusted the title of this issue to reflect as much.

Fix will be forthcoming in next release, thank you again for reporting this!
