### ISSUE TITLE
Chrome 32 Rollover

### ISSUE THREAD

**Issue by aduke** [jamietre/ImageMapster#178]
My rollovers are either not working or barely visible with Chrome now that version 32 has released.  Any ideas on a patch or workaround?

**Comment by techfg** [comment]
Hello @aduke -

Thank you for reporting this.  Per the follow-up conversation, it appears that this was resolved in Chrome 33.

Do you still require a fix for Chrome 32 or can we close this?

**Comment by techfg** [comment]
Hello @aduke -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.
