### ISSUE TITLE
Changing images and maps on a SPA (single page application)

### ISSUE THREAD

**Issue by glmason** [jamietre/ImageMapster#188]
Hi I was wondering if there was a way to change the image using a different image map in a Node.js/jquery application that is using mapster (great plugin by the way) ? I have tried several different combinations of changing element attributes but have not had success yet. Was wondering if anyone else has tried this.

**Comment by techfg** [comment]
Hello @glmason -

Apologies for the delay in circling back with you.

As @jamietre indicates, the server component of your application should not have any impact on IM functionality as IM is all client-side.  The way you describe your issue, it's likely that there is a condition in your JS that is relying on something else that is not yet available (e.g. external JS script downloading).  Examples of this would be incorrect (or not using)  the "ready" function, trying to interact with IM before its configured (e.g. using onConfigured callback), etc.  Compared to your dev box with everything local, things will load/retrieve a little slower when running on a remote server but outside of latency, nothing else should be impacted by the server your using.

Please let us know if this remains an issue for you and if so, please update this issue per our [Bug Reports]() guidelines.  Would be happy to investigate further but would require more information (e.g. your code) and a repro via [jsFiddle](https://jsfiddle.net) would be ideal.

**Comment by techfg** [comment]
Hello @glmason -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.
