### ISSUE TITLE
Adding buttons/links to the caption description? 

### ISSUE THREAD

**Issue by Lippiun** [jamietre/ImageMapster#196]
Hi. 

Does anyone know if you can add a link or button to the image caption? 

 paul: ["Test Heading 1",
                    "Lorem Ipsum is simply dummy text of the printing and typesettin"
                      + "Lorem Ipsum is simply dummy text of the printing and typesettin "
                      + "Lorem Ipsum is simply dummy text of the printing and typesettin"],

Thanks,

Shaun

**Comment by techfg** [comment]
Hello @Lippiun -

Thank you for your inquiry, apologies for the delayed reply!

I'm not exactly sure what you mean by "image caption," but I'm going to assume you mean the tooltip.

For tooltips, you can specify `string|jQuery` and as of v1.4.0, you can specify `string|jQuery|function`.  So, in order to have links/buttons in your tool tip, you could do something like the following:

```js
$('#myimg').mapster({
   mapKey: 'data-name',
   showToolTip: true,
   ....
  areas: [
   {
      key: 'paul',
      toolTip: $('<div/>').html(....)
  ]
}
```

Hope this helps.  If you have any further questions regarding general usage of IM, please see our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page for the best places to seek assistance.
