### ISSUE TITLE
Ipad issue

### ISSUE THREAD

**Issue by nikomouk** [jamietre/ImageMapster#198]
Hello,

i got an issue on ipad : the script is working on every browser, even on android, except on ipad & iphone (on both chrome and safari...).
The problem is on the onClick actoin that is not thrown on the apple mobile devices...
http://lamirand.nicolas-philippe.com/
Any idea ?

thanks.

**Comment by techfg** [comment]
Hello @nikomouk -

Thank you for reporting this, apologies for the delayed reply!

Unfortunately, the URL you provided is no longer active.  Please let us know if this is still an issue for you and if so, please update this issue per our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines so that we can investigate further.

**Comment by techfg** [comment]
Hello @nikomouk -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.
