### ISSUE TITLE
RE: Vegetable Tray Demo - Outputting an image or a more complex html instead of text

### ISSUE THREAD

**Issue by shelleyw** [jamietre/ImageMapster#199]
Hi - Thanks for making this great plugin!

I've managed to make a version of the Vegetable Tray Demo, but instead of outputting a block of text, is it possible to make it pull up an image in that box or put in a styled div of some sort? I apologize I'm kind of new to javascript/jquery things, any help would really be appreciated!

Here is what I have so far: http://jsfiddle.net/sb9j7/4083/

Thanks!

**Comment by techfg** [comment]
Hello @shelleyw -

Thank you for your inquiry, apologize for the delayed reply.

In reviewing your fiddle, I don't see anywhere that you've changed anything from the Vegetables example.  That said, yes, it's possible to render any HTML instead of text, all that is required is to generate the HTML that you'd like to render and place it in the desired target element.

Since your question is more of a general support issue than reporting a bug and/or asking for a feature, I'm going to go ahead and close this.  If you require further assistance of this type, please see our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page for various options.
