### ISSUE TITLE
State Legend Fill 

### ISSUE THREAD

**Issue by mayowaojo** [jamietre/ImageMapster#200]
Is it possible to have the state legends to the right of the map a different color/opacity/fill than the actual states. For instance when you select New Hampshire, for the state to be a solid color, and the label to be a different opacity or smaller fill?

Thank you in advance!

**Comment by techfg** [comment]
Hello @mayowaojo -

Thank you for the inquiry, apologies for the delayed reply!

From your question, it's unclear what you are referring to by "legend" and/or "label."  As an example, in the demo's the USA Map contains a bound list to the right of the map itself with all the states listed along with checkboxes.  Additionally, for some states such as New Hampshire, Maine, Vermont, etc. there are labels within the map itself located outside of the state (because they wouldn't fit within the state itself).  In short, not sure which "legend/labels" you are referring to.

I'll try to address both as best I can:

1) For the list with checkboxes - You can define a CSS pseudo-selector `:checked` that activates when the checkbox is enabled/checked that changes the css properties.

2) For the labels within the map itself (separate area elements), you can achieve your desired result a few different ways but all of them require implementing handlers for the various events that IM fires when certain things occur (e.g. onClick, onStateChange, etc.).  To demonstrate one way to achieve this, I've created a [fiddle](https://jsfiddle.net/techfg/4k08Ln3x/20/) that uses the onStateChange event.  If you click on "New Hampshire" (either via the "label area" or the "state area") the "label area" will end up with a different fillColor than the state itself.  The key portions to review are:
    1. I've added a "NH_Label" key to the list of keys for the "label area" element
    2. In the onStateChange handler, I've added conditional logic that calls the 'set` API to apply the different options to the area

Again, there are various methods of achieving this, all with their pros/cons, but unfortunately there's no "stock setting" and this does require a custom solution using the features that IM provides out of the box.

I hope this helps.  If you have any further questions and for future reference, please see our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page for options how to obtain support for general IM questions.
