### ISSUE TITLE
Show tooltip from bound link

### ISSUE THREAD

**Issue by kadoka66** [jamietre/ImageMapster#201]
Hi there, first of all would just like to thank you for making an awesome plugin. Before I begin I need to point out that I am a complete beginner when it comes to javascript. Here is my map so far http://sakenotabibito.com/?page_id=30#. Basically, I want to show a tooltip for each area of Japan when the user hovers over the links in the list below. I have only added 3 areas so far just to test. I have managed to get the tooltip working by hovering over the area itself but cannot get it to work from the outside link. If you can point me in the right direction, as simply as possible I would be very greatful.

**Comment by techfg** [comment]
Hello @kadoka66 -

Thank you for your inquiry, apologies for the delayed reply!

Unfortunately, the URL you referenced is no longer active so I'm unable to take a look at the code/config.  You indicate the tooltip was working on hover but I'm not sure what you mean by "from outside the link."  IM supports automatic tooltips but only on hover of the AREA element.

Can you provide more details on specifically what you are trying to achieve and unable to along with example via [jsFiddle](https://jsfiddle.net)?

For future reference, general usage questions are best suited for Stack Overflow rather than issues in this repo.  Please see our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page for a list of options for general support questions.

**Comment by techfg** [comment]
Hello @kadoka66 -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.
