### ISSUE TITLE
Checkboxes - Interaction

### ISSUE THREAD

**Issue by alexontheedge** [jamietre/ImageMapster#203]
Hi,

I am trying to setup check boxes to interact both ways with the map selections - Frustratingly, I am only able to get the checkboxes to check when the user clicks the map - For some reason this doesn't work properly when using the checkboxes... The checkboxes select the map states but do not tick the boxes.

Can someone please share their expertise and have a look at the link below:

http://jsfiddle.net/VHLBz/3/

Many thanks in advance.

**Comment by MB34** [comment]
Make this change:
```javascript
    $('.mapsterCheckbox').click(function () {

        var clickedCheckbox = $(this);
        clickedCheckbox.attr('checked', !clickedCheckbox.attr('checked'));
        $('#mapster').mapster('set', clickedCheckbox.attr('checked'), clickedCheckbox.attr('id'));

    });
```

**Comment by techfg** [comment]
Hello @alexontheedge -

Thank you for the inquiry, apologies for the delayed reply!

The reason you are experiencing the behavior you describe is due to an flaw in your javascript which is causing the checkbox state to change to its previous value after the user clicks the checkbox.  The reason for this is:

1) The `change` handler for the checkbox calls mapster to set the `selected` state of the State.
2) The `onStateChange` handler sets the state of the checkbox based on the now current `selected` state of the area. 

In short, #2 reverts the checkbox back to its previous checked/unchecked state.

As @MB34 describes, changing to use the `click` event instead of the `change` event for the checkbox should resolve your issue.

Hopeful that @MB34's guidance helped you resolve your issue.  If not, and you still have questions, please feel free to utilize one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page for general IM/javascript assistance.  If you feel you've identified a bug, please submit an issue per our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines and/or if you'd like to request a new feature, please submit a new issue per our [Feature Request](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.

Hope this helps!
