### ISSUE TITLE
Draggable image map in a smaller div

### ISSUE THREAD

**Issue by comatoze** [jamietre/ImageMapster#206]
Hello. I have a site where there’s a logo and a menu on the left, and an image map which utilizes ImageMapster on the right. The map is bigger than the div it’s inside, so the user should be able to drag it around (think of Google Maps).

I’ve managed to create the dragging effect with jQuery’s Draggable Widget (http://api.jqueryui.com/draggable/), but there’s a problem with it. When I drag the map, it doesn’t move smoothly but rather jumps straight to the other edge even with the littlest of mouse movement.

See fiddle (the black boxes are placeholders for logo and menu, don’t mind about them): http://jsfiddle.net/ZmqJ7/
Full screen: http://fiddle.jshell.net/ZmqJ7/show/light/

When I remove the ”containment” option the map does move smoothly but goes over the edges.

I’m not even sure this is the right place to ask this question as ImageMapster probably isn’t the culprit here, but since I am using said plugin and this could benefit other users as well, I thought I’d give it a shot.

**Comment by techfg** [comment]
Hello @comatoze -

Thank you for your inquiry, apologies for the delayed reply.

I took a look at your fiddle and replicated the behavior you describe (I had to swap the image to another one because the one you referenced was no longer available).  Given the behavior and the fact that eliminating the `containment` option provides "smoother" dragging, I'd have to guess that this issue is something to do with the Draggable widget and not IM as you mention.  I can't think of anything that IM could be doing that would cause this although I can say it's unlikely that IM was ever tested in this situation.

Were you ever able to resolve this?

**Comment by techfg** [comment]
Hello @comatoze -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.
