### ISSUE TITLE
On resize, the map exceeds the div container

### ISSUE THREAD

**Issue by Adyyda** [jamietre/ImageMapster#209]
Hello. I have a website in development wich has 2 blocks (left+right), responsive and 50% each. The map is in the left block. When i enter the page, the map shows ok but, if i resize the page, the map will go beyond the left block div, from a 500px width to 1700px for instance. 

How can i lock it's size so that the biggest size it takes is maximum 500px or prevent it from exceeding the div container? I spended 2 days and none of the things i tried works. Thanks

**Comment by tylla** [comment]
I was confronted with this same issue, where I want to create a responsive design.
The resize function has some unnecessary hardcoded width/height which makes it really hard to achieve the goal.
The code snippet given in #42 works only if the image is displayed fitting the whole width of the window. That's why the image will load properly sized, but will jump bigger at first resize.
As otherways this plugin is really awesome, I am currently busy trying to overcome these problems, I already managed some progress, but I can't seem to get it to work properly (the resize is slow and buggy).
With two small changes in jquery.imagemapster.js, the map follows the size of the wrap div, but the original image (the one that gets copied over inside the wrapper) still gets the same width/height inline style as the canvas elements get, and this way the resizing only works in small increments.
@jamietre can we get a little assistance?

**Comment by jamietre** [comment]
I haven't actually touched this in 3-4 years... there are a great many things that need modernizing. Integration with modern bundling tools like webpack/browserify doesn't really work either. I would love to dig into it but I'm not using it on anything I'm actively working on right now so I don't really have time. 

If anyone wants to be a contributor to the project and spend some effort modernizing and/or fixing bugs it I'd be glad to add you.

**Comment by techfg** [comment]
Basic auto-resize support as described in #359 was added in #360.
