### ISSUE TITLE
ImageMapster is changing the coord on hover effect

### ISSUE THREAD

**Issue by yaazkal** [jamietre/ImageMapster#212]
Hi. The issue that I'm experiencing is that the hover effect is changing the coords, so the image looks moved when you hover.

I've checked and image seems good. No width, height, position or anything on the image is changed. But coords are changed as you can see.

Site: http://dev.marcell.co

I can't get any way to troubleshoot that as I tested all that I know.

Thanks.

**Comment by techfg** [comment]
Hello @yaazkal -

Thank you for your inquiry, apologize for the delayed reply!

Unfortunately, the original URL you mentioned in your OP along with the image that @jamietre used in his fiddle are no longer available so I'm unable to provide an definitive answer to your question at this time.  

Per your OP, IM will not change the coords during hover so I'm not sure what was going on and/or what you were seeing.  Setting the width/height/max-width should not cause an issue with the current version of IM although its difficult to say for certain if it would have caused an issue with the version you were using since I'm not sure what version that was.  There are some issues with some css properties (see #358) but it doesn't appear you were using anything other than width/height/max-width.

Either way, if this is still an issue for you, if you could update this issue per our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines, we'd be happy to take a closer look.

**Comment by techfg** [comment]
Hello @yaazkal -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.
