### ISSUE TITLE
image map out of alignment

### ISSUE THREAD

**Issue by blackcat1975** [jamietre/ImageMapster#216]
I had the image map set up in html to get it working. I have had to move it into a wordpress page and the alignment has shifted. I can't seem to work out what I need to do to fix it.

http://newsite.wkwd.com.au/#staffmap

**Comment by techfg** [comment]
Hello @blackcat1975  -

Thank you for your inquiry, apologies for the delayed reply!

Unfortunately, the URL you specified is no longer active and you do not indicate what was actually wrong other than the fact that it wasn't working as you expected.  Without more details, I'm unable to determine what the issue was.

If this is still an issue for you, please update this issue per our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines and we'll be happy to investigate further.

**Comment by techfg** [comment]
Hello @blackcat1975 -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.
