### ISSUE TITLE
Multiple Maps not working in IE9

### ISSUE THREAD

**Issue by wlchiang** [jamietre/ImageMapster#217]
I have a page with 2 image maps - they're both working great in IE11, Chrome, and Firefox, but only one map is working in IE9. The image map & links function, but the imagemapster effects aren't kicking in. 

http://jitca.cbcs.usf.edu/index.shtml - California doesn't work, but the bubbles do. Any ideas on how to get both working? Many of our users are still in IE9 (some are earlier...), so I'd like to get it working if possible, even though it's an older browser.

**Comment by techfg** [comment]
Hello @wlchiang  -

Thank you for your inquiry and apologies for the delayed reply!

Unfortunately, the URL you mentioned is no longer active so I can't investigate.  With that said, there were some issues with earlier versions of IM related to multiple maps which have since been addressed.

If this is still an issue for you, please update this issue per our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines using the latest version of IM and we'll be happy to investigate further.

**Comment by techfg** [comment]
Hello @wlchiang -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.
