### ISSUE TITLE
Variable fill color on hover

### ISSUE THREAD

**Issue by jdeproost** [jamietre/ImageMapster#223]
Hello,

I'm trying to implement an image map that has a green(ish) fill-color on hover for available area's and red fill-color on hover for none available area's.

I tried to use the keys but did not succeed...
Can someone provide a short example?

Thanks,
Johnny

**Comment by techfg** [comment]
Hello @jdeproost -

Thank you for your inquiry, apologies for the delayed reply!

For further reference, the best place to ask general support questions on IM is to utilize one of the options as described in our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.

With that being said, you can accomplish what you are after.  You can do so via using the `areas` option and specifying different `render_select`/`render_highlight` fill colors based on `mapKey`.  Additionally, you could use onmouseover event and the `set_options` API to specify the fill color for a particular area.  Please see the [docs](http://www.outsharked.com/imagemapster/default.aspx?docs.html) for more information about these options & APIs.

It sounds like you were trying this but it wasn't working.  If you feel it wasn't working because of a possible bug in IM, please update this ticket per our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines and we'd be happy to take a closer look.

**Comment by techfg** [comment]
Hello @jdeproost -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.
