### ISSUE TITLE
tooltip hover problem  

### ISSUE THREAD

**Issue by nicolainmateria** [jamietre/ImageMapster#226]
Hi, i'm using image mapster on my new project:
http://www.ltllenses.it:81/en/company/#LTL_map_img_wrap
but I've troubles with some areas (for example the Americas area, above alaska) because the tooltip appears above the active area, than I can't move inside the entire area.

Is it a way to assign an ID to every tooltip and change their position with css? Or any other solution to avoid this problem?

**Comment by MarkGCarr** [comment]
Hi Nicolainmateria,

So glad I found this tread. I've created a nice simple map with Imagemapster but can't successfully incorporate tooltips into the maps, and how I can then style those tool tips with CSS. Can you offer any suggestions on how to properly do this, or perhaps where I can get more information? I've tried downloading tooltip software from Code Canyon, but none of the programs appear to be compatible with Imagemapster, or at least I haven't been able to get them to work. Ideally I'd prefer to do it all in Imagemapster, but can't get it work as of yet.

Thanks.

Mark

**Comment by Kbam7** [comment]
Hey MarkGCarr, i have managed to figure the tooltip function out. 

Follow this link for instructions: http://www.outsharked.com/imagemapster/docs.html#tooltip-options

Near the top of the page you will find a little bit more info on tooltips, but you basically only need the tooltip options.

I was able to modify the tooltips appearance and also edit how it displays and hides.

You must use "toolTipContainer" to allow for custom editing. For example, add this as an option : toolTipContainer: '<div class="my-custom-tooltip"> ... </div>' .... This will put a div tag around the tooltip with the class name "my-custom-tooltip". From there you can customize your tooltip.

Please note that these are the default styles used for the default tooltip:

    border: 2px solid black;
    width: 160px;
    padding: 4px;
    margin: 4px;
    box-shadow: rgb(83, 83, 83) 3px 3px 5px;
    border-radius: 6px;
    opacity: 0.899999976158142;
    display: block;
    position: absolute;
    left: 604.78125px;
    top: 1237.0625px;
    z-index: 9999;
    background: rgb(238, 238, 238);

When you assign a new element and class name (toolTipContainer: '<div class="my-custom-tooltip"> ... </div>'), the default styling is removed and you may not be able to see the tooltip. I suggest adding the above default styles to your custom tooltip class(.my-custom-tooltip) and then customize from there. 

Please let me know if this solved your problem by replying to this thread Thank you! :smile:

**Comment by Kbam7** [comment]
Hey nicolainmateria, are you still having problems? Let me know if you need some assistance and i will see what i can do for you

**Comment by phillystyle123** [comment]
@Kbam7 is there a way to style tooltips differently on the same page? For instance, If I want to position one differently than the other or have each tool tip have it's own different bg color?

**Comment by techfg** [comment]
Hello @nicolainmateria -

Thank you for your inquiry and apologies for the delayed reply.

Did the information that @Kbam7 provide you resolve your issue?

@phillystyle123 - You can style tooltips differently by either modifying toolTipContainer at runtime or another option is instead of using a literal string for `toolTip` you can specify a jQuery object (e.g., $('<div/>').html('....') and this way each tooltip can have it's own shape/style.  Also, as of v1.4.0, IM allows the toolTip to be a function (in addition to string & jQuery object) providing for further customization opportunities.

**Comment by techfg** [comment]
Hello @nicolainmateria -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.
