### ISSUE TITLE
Select an area on click of list at the same time highlight all the areas on first load.

### ISSUE THREAD

**Issue by uttaras** [jamietre/ImageMapster#231]
Hi,

I have referred your below example:
http://jsfiddle.net/jamietre/gjH5c/

I need exactly same functionality.
but change is highlight all the areas on load. Hence used staticState: true.
But use of the above option disabled effect of area highlight on click of the listed item. 
Here on click of list item, I want to highlight/select that corresponding area but at the same time keep the highlighting of other areas as it is with less opacity.

I tried changing the code for mapster as below:

var img=$('img').mapster({
   mapKey: 'state',
    singleSelect: true,
    render_highlight: {
            fillOpacity: 0.8
        },
        render_select: {
            fillOpacity: 0.4
        },
            staticState: true,
            singleSelect: true,
});

Thanks a lot in advance,
Uttara

**Comment by techfg** [comment]
Hello @uttaras -

Thank you for your inquiry, apologies for the delayed reply!

In reviewing your question, I'm not 100% certain what you are trying to achieve.  With that said, I noticed in your code that `singleSelect === true` which would result in only one area being able to be selected at a time.  If you set this to `false` multiple areas can be selected via the list.

However, as you mention, when `staticState === true`, mouse events are disabled as mentioned in the [docs]().

So its unclear exactly what you would like to achieve.

If you can provide more specifics and possibly even screenshots, we'll try to help further.  Also, as mentioned in our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page, general questions such should utilize one of the support options mentioned there.

**Comment by techfg** [comment]
Hello @uttaras -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.
