### ISSUE TITLE
Centering an ImageMapster-generated image map

### ISSUE THREAD

**Issue by nrabreu** [jamietre/ImageMapster#242]
Hello!

I'm experimenting with using ImageMapster while putting together a website for a friend. As part of this, I set up a simple "home" page, with the intent of using an image map in addition to the nav bar.

I've been trying for a while to center the image map (much in the way that the page's text is centered), but unfortunately, I can't seem to get it to work, and when tweaking the width of the canvas manually (from 488px to 100%), the image is centered but the hotspots are way off.
 
What would you suggest?

Thanks!
N.A.

**Comment by GitGianluc** [comment]
Hi @nrabreu! I've experienced the same problem (due to the fact that ImageMapster wraps the images within a &lt;div&gt; container) and I found a quick workaround.

Just browse /src/mapdata.js file and:
• **Step 1**. Go to line 630 `wrap = $('<div id="' + me.wrapId() + '"></div>');` and add a CSS class to the &lt;div&gt; tag:
```javascript
wrap = $('<div class="whatever-you-want" id="' + me.wrapId() + '"></div>');
```
This will allow you to define a proper set of CSS rules for every "ImageMapsterized" image.

• **Step 2**. Go to lines 672-676 and comment lines 672 & 647 as follows, in order to override unwanted styling rules:
```javascript
css = {
  // display: 'block',
  position: 'relative',
  // padding: 0,
  width: scale.width,
  height: scale.height
};
```

Hope this helps,

Gianluca

**P.S.**: if you got the jquery.imagemapster.js file from the /dist/ directory, Step 1 refers to line 3196; Step 2 refers to lines 3238-3242.

**Comment by techfg** [comment]
Hello @nrabreu -

Thank you for your inquiry, apologize for the delayed reply!

As @GitGianluc mentions, IM wraps the `img` in a `div` so CSS you've applied to the `div` will be lost unless you utilize either the `wrapClass` or `wrapCss` configuration options.  Please see the [docs](http://www.outsharked.com/imagemapster/default.aspx?docs.html) for more information.
