### ISSUE TITLE
issue with alt-images

### ISSUE THREAD

**Issue by trackme-lloyds** [jamietre/ImageMapster#243]
I can't see the alt-ed image in the background... even with this example of altimages. Nothing changes i don't get any background image changed.. 

However.. im using for my website trifecta.imagemap... 
I've got this so far: http://lloyds-design.hr/dinastija/
But what I want is when I hover ( or onmouseover) one of the objects... I want ground plan in the red box of the object to appear. And IMPORTANT: these apartments are not 3 images it's one! and it's whole html background! 

Here's the code: 

```
                        <img id="myImageMap" src="images/back.jpg" usemap="#shapesMap">
                        <map name="shapesMap">                                 

                           <area data-mapid="1" coords="1693,303,1871,446,1887,702,1703,760,1347,708,1356,594,1298,597,1302,552,1358,542,1362,479,1306,495,1309,440,1492,402" alt="Triangle" href="#" shape="poly" />

                           <area data-mapid="2" coords="1042,729,1038,593,1114,602,1111,556,1037,533,1035,460,1108,499,1108,444,908,299,792,300,643,415,642,733,698,756,879,715,1010,737"  alt="Square" href="#" shape="poly" />
                            <div class="object">
                           <area data-mapid="3" coords="298,365,505,475,574,486,590,689,405,719,289,694,187,711,165,709,169,599,111,604,114,565,168,552,174,493,116,515,118,469"  alt="Circle" href="#" shape="poly" />            
                            <div class="dot"></div>
                             <div class="pulse"></div>
                           </div>
                        </map>
```

And here is the script I used to get this: https://github.com/nswilhelm/jquery-map-trifecta

Need help with that as soon as possible.. thank you! :)

**Comment by techfg** [comment]
Hello @trackme-lloyds -

Thank you for your inquiry, apologies for the delayed reply.

Unfortunately, your website URL is no longer active so I can't review the behavior.  Additionally, you mention you use the jquery-map-trifecta but that has nothing to do with IM so I'm a little confused.

If this is still an issue for you and you are using ImageMapster, please update this issue per our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines and we'd be happy to evaluate further.

**Comment by techfg** [comment]
Hello @trackme-lloyds -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.
