### ISSUE TITLE
imagemapster not working with ASP.Net Validation

### ISSUE THREAD

**Issue by hardycyr** [jamietre/ImageMapster#246]
Hello,

I am trying to use imagemapster within ASP .Net web application and it looks like this doesnt work with ASP .Net validation.
I keep getting the error "Uncaught TypeError: $(...).mapster is not a function"
Then, if I remove the validator asp:RequiredFieldValidator, everything works as expected.
Am I doing something wrong ?

Thanks a lot in advance for your answer,
Best regards,
Cyrille

**Comment by PaschoalOliveira** [comment]
I have the same problem here. Have you found a solution?

**Comment by dahashimoto** [comment]
Unfortunately not yet. I can get the data into my console but then am
having trouble getting that data to transmit through form to SQL.

Any thoughts?

**Comment by dahashimoto** [comment]
Sorry, responded to wrong thread.

**Comment by techfg** [comment]
Hello @hardycyr  -

Thank you for reporting this, apologies for the delayed reply!

IM should not have any issues when ASP.Net Validation is being used, however without more details and a code sample/repro, its difficult to say for certain what is going on.  What is clear is that the reason you encountered the `Uncaught TypeError: $(...).mapster is not a function` is because the IM was not loaded in to the current jQuery instance you had on the page.  The reasons for this are unknown without a code sample/repro.

Please update this ticket per our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines and we'd be happy to investigate further.

**Comment by techfg** [comment]
Hello @hardycyr -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.
