### ISSUE TITLE
All Tooltips activated on load

### ISSUE THREAD

**Issue by Webtransformer** [jamietre/ImageMapster#247]
I can´t find the answer for my problem.
I have two areas each with a tooltip. I manage to display one tooltip open/active when the page loads with this:
...
        toolTip: true,
        showToolTip: true,
        toolTipClose: [""],
...
.mapster('tooltip',"key");

But I want to open all Tooltips when the page loads? Has someone a hint for me?

**Comment by techfg** [comment]
Hello @Webtransformer  -

Thank you for your inquiry, apologies for the delay reply.

IM only supports a single tool-tip being visible at a time.  If you'd like to have all tooltips open on page load, I'd recommend you  utilize a tooltip library to control that desired behavior rather than using IM for tooltips.

Hope this helps!
