### ISSUE TITLE
"Uncaught Can't access data until binding complete."

### ISSUE THREAD

**Issue by boxgames1** [jamietre/ImageMapster#255]
Hi, I have a problem with the ImageMapster in a situation where I have at least 4 maps, the 4th crashes with the following error code in the JS console: 

jquery.imagemapster.js:1407 Uncaught Can't access data until binding complete.

As seen in a previous issue I configured the mapster:

```
onConfigured: function() {
                realOpts = getRealOpts(map_img);
                map_img.mapster('snapshot').mapster('rebind', realOpts, true);
}
```

In getRealOpts I set the configuration vars and make some business logic, however this is still crashing in the 4th map.

TIA

**Comment by techfg** [comment]
Hello @boxgames1  -

Thank you for your question, apologies for the delayed reply!

Without more details including visibility to more of your code, its difficult to say what the issue is.  As described in #346, there is a current issue with IM where it allows methods to be called on an element even when IM hasn't been initialized yet.  In this situation, IM will sometimes return successfully and sometimes encounter the error you describe.

My only guess at this point is that you are calling `snapshot` and `rebind` but did not initialize IM yet via (`map_img.mapster({...})`).

Beyond that, we would need more information to further investigate so if this is still an issue for you, please update this issue per our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines and we'd be happy to investigate further.

**Comment by boxgames1** [comment]
Lol "delayed". I stopped using this library 4 years ago so will close the issue
