### ISSUE TITLE
Highlight nested areas

### ISSUE THREAD

**Issue by m-juenger** [jamietre/ImageMapster#264]
On a map where are nested states like in germany, there is a problem highlighting only the outer or inner state.

For example: Berlin is a town but also an own federal state and is located within the state of Brandenburg. The same we have with Bremen which is also both, a town and an own federal state which is located within the state of Lower Saxony.

If I highlight Brandenburg, Berlin will also be highlighted but should not be.
To solve this I set a data attribute on each area where I could define a state which should be excluded on highlighting or selecting the state. This way I could exclude Berlin on highlighting Brandenburg for example but unlikely I can't see an appropriate way to set the color of an area. Therefore I would like to have a method to set the color of an area and this should have a higher priority than highlight or select.
Could be a method like highlight. Highlight itself would work but only works on highlight and not on select.

Kind regards,

Michael

**Comment by techfg** [comment]
Hello @m-juenger -

Thank you for your inquiry, apologies for the delayed reply!

I think I follow what you are trying to do but I'm not exactly sure.  Without a visual representation of which area you want and don't want its difficult to say for certain but based on what I think you want, one key is to make sure the `primaryKey` (the first value in your mapKey data attribute) is unique for all areas.  Additionally, you can use the [includeKeys](http://www.outsharked.com/imagemapster/default.aspx?docs.html#showtooltip) option as possible partial/complete solution and even possibly the mask related options so you can exclude certain areas that are "inside" and area that is currently highlighted/selected.

Beyond that, you'd need to provide more specifics including screenshots of what you are looking to achieve along with code samples for us to further evaluate/inform.

**Comment by techfg** [comment]
Hello @m-juenger -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.
