### ISSUE TITLE
bag after resize

### ISSUE THREAD

**Issue by letsgosesh** [jamietre/ImageMapster#267]
I decided to see how the script works.
And here I can not solve the problem.

OK - http://prntscr.com/d74djt
NOT OK http://prntscr.com/d74eck

after resizing dressed area leaving a few pixels
what could be the problem?

**Comment by techfg** [comment]
Hello @letsgosesh -

Thank you for reporting this!  Unfortunately, while I can visually see the issue in the screencaptures you provided, I'm unable to determine what the underlying issue might be.

Please provide a full repro in the form of a [jsFiddle](https://jsfiddle.net/) and I'll be happy to take a closer look.

Thank you!

**Comment by techfg** [comment]
Hello @letsgosesh -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.
