### ISSUE TITLE
Area Coordinates Altering Automatically

### ISSUE THREAD

**Issue by bilzhere** [jamietre/ImageMapster#268]
I have used the following code for highlight MAP Areas on mouse over. 

`_### function showPop(index){
	var imglc = "/dvdms/images/district_manipur/"+maps[index];
	  $('#distimage').attr('src',imglc);
	  $('#distname').html('<b>District Name: </b>'+district[index]);
	  $('#distimagemap').empty();
	  $('#distimagelist').empty();
	  var i;
	  var xmlDoc = xml.responseXML;
	  var x = xmlDoc.getElementsByTagName("marker");
	  var dist = index;
	  var str = "";
	  for (i = 0; i <x.length; i++) { 
	   if(parseInt(x[i].getAttribute('district'))==dist){
		   var cd = (parseInt(x[i].getAttribute('x'))) +","+(parseInt(x[i].getAttribute('y')))+",15";
		   str = "<area shape=\"circle\" data-name=\""+x[i].getAttribute('data')+"\" ";
		   str = str + "coords=\""+cd+"\" href=\"#\" alt=\""+x[i].getAttribute('name')+"\">";
		   $("#distimagemap").append(str);
		   var ar1 = [x[i].getAttribute('name'),x[i].getAttribute('address'),"s"+dist];
		   all_info[i] = ar1;
	   }
	  }
	var total = 0;
	var area = "{\"areas\":[";
	$('#distimagemap').children('area').each(function () {
	   var id = $(this).attr("data-name").split(',');
	   var ind =  id[0].split('s');
	   total++;
	   $('#distimagelist').append("<button class=\"button\">"+all_info[(ind[1]-1)][0]+"</button>");
       area = area + "{\"key\":\""+id[0]+"\",\"toolTip\":\"<b>"+all_info[(ind[1]-1)][0]+"</b>\"},";	     
	});
	alert($('#distimagemap').html());
	$('#distimagelist').prepend("<div style=\"width:80%;margin-left:auto;  margin-right:auto; border-radius: 5px;text-align: center; margin-bottom: 2px;margin-top: 2px;\"> <b>Total Store:</b> "+total+"</div>");
	area = area.substring(0,area.length-1)+"]}";
	
	var inArea,
    map = $('#distimage'),
    single_opts = {
        fillColor: '000000',
        fillOpacity: 0,
        stroke: true,
        strokeColor: 'ff0000',
        strokeWidth: 2
    },
    all_opts = {
        fillColor: 'aed1c9',
        fillOpacity: 0.6,
        stroke: true,
        strokeWidth: 2,
        strokeColor: 'd50bc8'
    },
    initial_opts = {
        mapKey: 'data-name',
        isSelectable: false,
        showToolTip: true,
        toolTipClose: ["tooltip-click", "area-click"],
        onMouseover: function (data) {
        	
            inArea = true;
            var ind =  (data.key).split('s');
            $('#distimageinfo').html("<u><b>"+all_info[(ind[1]-1)][0]+"</b></u><br/><br/><br/>"+all_info[(ind[1]-1)][1]);          
            map.mapster('set_options',JSON.parse(area));
        },
        onMouseout: function (data) {
            inArea = false;
        }
    };
opts = $.extend({}, all_opts, initial_opts, single_opts);

map.mapster('unbind')
    .mapster(opts)
    .bind('mouseover', function () {
        if (!inArea) {
            map.mapster('set_options', all_opts)
               .mapster('set',true, 'all')
               .mapster('set_options', single_opts);
        }
    }).bind('mouseout', function () {
        if (!inArea) {
            map.mapster('set', false, 'all');
        }
    });	
alert($('#distimagemap').html());
}_`I am making areas dynamically from an XML file. but before the following code it is alerting correct code.

map.mapster('unbind')
    .mapster(opts)
    .bind('mouseover', function () {
        if (!inArea) {
            map.mapster('set_options', all_opts)
               .mapster('set',true, 'all')
               .mapster('set_options', single_opts);
        }
    }).bind('mouseout', function () {
        if (!inArea) {
            map.mapster('set', false, 'all');
        }
    });	
after This code it is changing area coordinates value.  So I found mapstar is  doing something wrong. You guys have a look on this issue.

**Comment by techfg** [comment]
Hello @bilzhere -

Thank you for reporting this and apologies for the delayed reply!

Unfortunately, the code in your OP was not formatted correctly so its difficult to follow and therefore difficult to say exactly what is really going on.  With that said, by default, ImageMapster will automatically scale AREA coordinates to the size of the image that is being displayed.  This is normally what you'd want otherwise your AREA regions will not align with the visual image.  If you do not want IM to auto-scale, you can disable by setting the configuration option [scaleMap](http://www.outsharked.com/imagemapster/default.aspx?docs.html#scalemap) to `false` per the docs.

Hope this helps.   If not, if you could provide more details per our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines, we'd be happy to take a closer look.

**Comment by techfg** [comment]
Hello @bilzhere -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.
