### ISSUE TITLE
Keep altImage selected onmouseout

### ISSUE THREAD

**Issue by phillystyle123** [jamietre/ImageMapster#272]
The altImage appears when I hover over either of the "i"s on this page: [http://cjehost.com/qt/nipt/page10.php](url). I need the altImage to stay turned on when I mouseout. So, the altImage needs to be turned on onmouseover and stay on even after onmouseout.

**Comment by phillystyle123** [comment]
Hi jamietre - any thoughts on this? It seems like it should be fairly easy to do.

**Comment by phillystyle123** [comment]
I figured out how to use onMouseOut in the overall javascript - is there a way to add onMouseout to specific areas? 

This works:

$('img').mapster({
        staticState: false,
		showToolTip: true,
        noHrefIsMask: false,
        onStateChange: state_change,
		fill:false,
        fillColor: 'ffffff',
        fillOpacity: 0,
        mapKey: "group",
        strokeWidth: 2,
        stroke:true,
        strokeColor: 'f27821',
        render_select: {
            fillColor: '000000',
            fillOpacity: 0.2
        },
		
onMouseout: function (e) {
         if(!$(this).hasClass('hithere')){
            $('.hithere').html('<img src="http://cjehost.com/qt/nipt/images/pan-page8-overlays-1300.png" class="img-responsive" border="0" alt="" usemap="#panorama">');
         }},

This does not:

key: 'info1',
				includeKeys: 'info1over',
				stroke: false,
				fill:false,
                strokeWidth: 1,
				fillOpacity: 1,
				strokeColor: 'f27821',
				strokeWidth: 2,
				isMask: false,
onMouseout: function (e) {
         if(!$(this).hasClass('hithere')){
            $('.hithere').html('<img src="http://cjehost.com/qt/nipt/images/pan-page8-overlays-1300.png" class="img-responsive" border="0" alt="" usemap="#panorama">');
         }},

**Comment by phillystyle123** [comment]
any ideas? Possible to create something like "altImage2" and adjust code so the altImage stays "on" onmouseout?

**Comment by jamietre** [comment]
Hi - I'm sorry but I have not done any development on imagemapster in years, it would take me a long time to even remember how this works to answer your question. 

IIRC you should be able to control the image selection state manually by capturing the mouse enter/leave events and just set the state using `set`. If you haven't already take a look at the examples under "fiddle with it" in "demos" on the web site.

Other than that I apologize - I really can't help. I haven't looked at this in years, and I don't have time to get up to speed again to answer qeustions.

**Comment by phillystyle123** [comment]
Percisely why I chose it. My client needed something that would work back to ie8. Thanks for getting back to me. I'll try my luck with set although I'm finding customizing altImage to be a bit tricky.

**Comment by techfg** [comment]
Hello @phillystyle123 -

Were you ever able to follow the guidance that @jamietre provided and get this working?  As he described, using `set` should be able to accomplish what you are trying to achieve if I'm understanding correctly.

**Comment by techfg** [comment]
Hello @phillystyle123 -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.
