### ISSUE TITLE
No feedback when using areas without href

### ISSUE THREAD

**Issue by denshade** [jamietre/ImageMapster#281]
When using areas without a href nothing works. Perhaps this is a rookie mistake on my part but a simple warning or error in the logs could have saved my 4 hours I spent figuring this out.

**Comment by techfg** [comment]
Hello @denshade -

Thank you for your feedback, apologies for the delayed reply and trouble you encountered.

As described in the [docs](http://www.outsharked.com/imagemapster/default.aspx?docs.html)

```
When nohref is specified on an area tag, that area is specifically excluded from the hotspot of any area that encompasses it. It will not respond to mouse events, and will not be highlighted. This can be used to create "holes" in hotspots. By default, ImageMapster will treat any area with nohref or no href tag as masks, the same as if this option had been applied.
```

So the behavior you encountered wouldn't justify a warning or error in the log since it's a valid and expected scenario.

With that said, we are working on launching a new website (#322) and I do believe that making this information more prominent in the docs would be beneficial.
