### ISSUE TITLE
Mapster highlight fade-out

### ISSUE THREAD

**Issue by stalkeron** [jamietre/ImageMapster#282]
Is it possible to have a fade-out effect when the highlight goes off when I go with mouse-out?

Would be the same as the fade-in effect with the duration I can set with fadeduration: 500;
can I somehow get that at the mouse-out event?

Could someone modify the script in such a way?

thank you

**Comment by techfg** [comment]
Hello @stalkeron  -

Thank you for your suggestion and apologies for the delayed reply.

IM doesn't not currently support fade-out on mouse-out but to answer your question, yes, it would be possible.

Happy to accept a PR if you'd like to contribute this feature!

**Comment by techfg** [comment]
Hello @stalkeron -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.
