### ISSUE TITLE
Using multiple image maps

### ISSUE THREAD

**Issue by canadianloonie** [jamietre/ImageMapster#283]
I have an image map with three clickable areas on it. I'm trying to make it so that when one of the areas is clicked, a unique image map will appear below it. If another area is clicked on the first map, another unique map will appear. In other words, each of the three clickable areas will display its own separate image map.

Someone asked a question similar to this and an answer was provided by showing and hiding divs:
https://stackoverflow.com/questions/20648701/imagemapster-with-multiple-images-and-maps

I tried this and it works, however it doesn't help with my issue since I want a different image map to appear depending upon which of the three selectable areas the user clicks on in the first map. The demo linked to on the imagemapster website (http://brickell-realty.com/epic.html , under "residences") is essentially what I'm looking to do, just without table below.

**Comment by techfg** [comment]
Hello @canadianloonie -

Apologies for the delayed reply!

Your question is better suited for Stack Overflow since it's asking for general support (e.g., how to) of IM and really more specifically javascript.  For future reference, you can check out our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page for details on the best ways to get support.

With that said, if I'm understanding what you were/are trying to do, you'd need to modify the onClick function in the SO post that you referenced and conditionally show/hide divs based on which area on your map was clicked.  You could achieve knowing which AREA was clicked by inspecting the `data` param passed in to onClick and then based on the `key`, show/hide your other divs.

Hope this helps.  If you have any further questions I'd recommend SO but please do let us know if you are encountering a bug/issue with IM that is preventing you from achieving your desired result.
