### ISSUE TITLE
ImageMapster does not work

### ISSUE THREAD

**Issue by maxg5** [jamietre/ImageMapster#284]
Hello!
The site [http://mosoblvoop.com](url)  does not work ImageMapster plugin.
The console displays the following errors:
**Uncaught TypeError: map.size is not a function
     At HTMLImageElement. <Anonymous> (jquery.imagemapster.js: 1777)
     At Function.each (jquery.min.js: 2)
     At r.fn.init.each (jquery.min.js: 2)
     At r.fn.init. $. Mapster.impl.me.bind (jquery.imagemapster.js: 1751)
     At r.fn.init. $. Fn.mapster (jquery.imagemapster.js: 836)
     At (index): 299**
Please help me with the problem.

**Comment by fagerbua** [comment]
You can fix this by changing `map.size()` to `map.length` in the library code. 

This problem appears to have been fixed in the master branch, cf. https://github.com/jamietre/ImageMapster/commit/740106939449dd0af48edc039a98e83972594a81. Thus simply using the javascript files from the `dist` folder might do the trick:
https://github.com/jamietre/ImageMapster/tree/master/dist

**Comment by techfg** [comment]
@fagerbua is correct, this was addressed back in June 2016 and is available in the latest dist.  The fix will be officially released in version 1.2.14.

**Comment by techfg** [comment]
Resolved in this [commit](https://github.com/jamietre/ImageMapster/commit/740106939449dd0af48edc039a98e83972594a81) and included as of [v1.2.14-beta1](https://github.com/jamietre/ImageMapster/releases/tag/v1.2.14-beta1).
