### ISSUE TITLE
Not compatible with SVG images in chrome

### ISSUE THREAD

**Issue by cotillardq** [jamietre/ImageMapster#285]
When used in chrome the images size seems to not be determined and the mapping no longer works.

**Comment by techfg** [comment]
Hello @cotillardq -

Thank you for reporting this, apologies for the delay resply!  

I'm not sure if IM was ever intended/tested to work with SVG images but I don't see any reason at a high-level that it wouldn't work. 

Unfortunately, without more details on what actually was not working and a repro of the problem its difficult to speculate.  If this is still an issue for you, if you could update this issue per our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines, I'd be happy to take a closer look.

**Comment by techfg** [comment]
Hello @cotillardq -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.
