### ISSUE TITLE
Image in a tooltip

### ISSUE THREAD

**Issue by cl99** [jamietre/ImageMapster#286]
I am using imagemapster. I want to use images in tooltip.  I managed to achieve that but tooltip is  not positioning correctly. It just slips way down. How can i position it according to the mapped area.

**Comment by techfg** [comment]
Hello @cl99 -

Thank you for your inquiry, apologies for the delayed reply!

Unfortunately. "slips way down" doesn't tell me very much and without a repro or more specific information, its difficult to say what the issue might be.  If this is still an issue for you, if you could update this issue per our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines, we be happy to take a closer look.

**Comment by techfg** [comment]
Hello @cl99 -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.
