### ISSUE TITLE
ImageMapster is not working with BootStrap

### ISSUE THREAD

**Issue by rashfmnb** [jamietre/ImageMapster#287]
ImageMapster is not working with BootStrap please tell me how to do it as soon as i include the BootStrap CSS and JS it stops working is there any work around

**Comment by techfg** [comment]
Hello @rashfmnb -

Unfortunately, you haven't provided any details regarding what is not working.  Please provide more details and include a repro via jsFiddle and we can take a look.

**Comment by techfg** [comment]
Hello @rashfmnb -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.
