### ISSUE TITLE
 $.mapster_when is undefined

### ISSUE THREAD

**Issue by DRAJI** [jamietre/ImageMapster#291]
Hi Admin,

Its a Fantastic feature for Image mapping. I have tried it in outside of magento. Its working rocks. But I have been trying to use this js in my magento2 module, its showing an error like  **$.mapster_when is undefined**

Could you support me to integrate this fantastic feature with my magento2 module? 

Thanks in advance!

**Comment by techfg** [comment]
Hello @DRAJI -

You haven't indicated how imagemapster is being loaded but given the error message, it is likely trying to be loaded as a module as opposed to just in browser script tag.

ImageMapster v1.3.0 introduces full UMD support allowing it to be loaded as a module.

Please try using the [latest version](https://github.com/jamietre/ImageMapster/releases/latest) of imagemapster and let us know if the issue persists.

**Comment by techfg** [comment]
Hello @DRAJI -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.
