### ISSUE TITLE
Positioning of Tooltip Center Top

### ISSUE THREAD

**Issue by glenpig** [jamietre/ImageMapster#294]
Hi

I've got everything working perfectly apart from the positioning of the tooltip.

Is there any way I can get the tooltip to position center of the hotspot and slightly above it?

So...
![tooltip-before](https://user-images.githubusercontent.com/33065237/39480362-e182e740-4d5f-11e8-9f35-198e7fc482dd.png)

becomes...
![tooltip-after](https://user-images.githubusercontent.com/33065237/39480370-e717a52e-4d5f-11e8-9f21-43d0dfb6aa5e.png)

Many thanks

**Comment by techfg** [comment]
Hello @glenpig -

Thanks for your question, apologies for the delayed reply.

I'm not sure if this is a bug or a feature requested based on the information you've provided thus far.  I'm not too famiiar with the tooltip positioning logic but I do know its somewhat limited/fragile.  If you could provide a full repro of your scenario per our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines, we'd be happy to take a closer look at evaluate further.

**Comment by techfg** [comment]
Hello @glenpig -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.
