### ISSUE TITLE
How to remove image from imagemapster

### ISSUE THREAD

**Issue by anjalirawat11** [jamietre/ImageMapster#296]
i am adding a imagemapster on an image dynamically. and i want to remove it on some button click.
how to clear an mapster?

**Comment by techfg** [comment]
Hello @anjalirawat11 -

Please use the 'unbind' method to remove imagemapster from an image:

$('img').mapster('unbind');

More information on unbind in the [docs](http://www.outsharked.com/imagemapster/default.aspx?docs.html) and you can find an example of its usage [here](http://www.outsharked.com/imagemapster/examples/usa.html).

**Comment by techfg** [comment]
Hello @anjalirawat11 -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.
