### ISSUE TITLE
Select is removed when clicked

### ISSUE THREAD

**Issue by abhion** [jamietre/ImageMapster#307]
When I click on the "selected" area, the stroke is removed.  How do I make it stay even when the area is clicked?

**Comment by techfg** [comment]
Hello @abhion -

Per the [docs](http://www.outsharked.com/imagemapster/default.aspx?docs.html), by default, a stroke is not applied to either "highlight" or "select".  You indicate that the stroke is removed on select but it's unclear if you have configured imagemapster to apply stroke on highlight.  

The following configuration will result in stroke being applied for both highlight & select:

$('#myimg'.).mapster({ stroke: true });

You can also provide specific instructions for highlight and select behavior:

```
$('#myimg').mapster({
    stroke: true,
    render_highlight: {
       stroke: false
    },
    render_select: {
      strokeWidth: 10
    }
});
```

If the above doesn't resolve your issue, please provide a [jsFiddle](https://jsfiddle.net/) with a repro.  Thank you!

**Comment by techfg** [comment]
Hello @abhion -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.
