### ISSUE TITLE
Change tooltips dinamically

### ISSUE THREAD

**Issue by rcaguirreg** [jamietre/ImageMapster#369]
I'm trying to update the tooltip of an area. The map is one floor of one building. 
![place_selected](https://user-images.githubusercontent.com/2381182/107552887-1409e980-6ba2-11eb-94d7-546b7c6c108f.PNG)

The "onClick" event opens a jQuery dialog box. 
![place_click](https://user-images.githubusercontent.com/2381182/107556195-18d09c80-6ba6-11eb-9314-2252c4688ff0.PNG)

You can select the day or days the place will be available to reserve. I need to update the tooltip according to the day(s) selection in the dialog box.

Below you can see the code of the button that save the changes
```
       // Object with the options for 'day'
       var days={
	        mon:{lang:'Monday', fillColor:'ff0000', stroke:false, strokeColor:'ffffff', strokeWidth:0}, 
	        tue:{lang:'Tuesday', fillColor:'ff8000', stroke:false, strokeColor:'ffffff', strokeWidth:0}, 
	        wed:{lang:'Wednesday', fillColor:'006600', stroke:false, strokeColor:'ffffff', strokeWidth:0}, 
	        thu:{lang:'Thursday', fillColor:'00bfff', stroke:false, strokeColor:'ffffff', strokeWidth:0}, 
	        fri:{lang:'Friday', fillColor:'0000ff', stroke:false, strokeColor:'ffffff', strokeWidth:0}, 
	        sat:{lang:'Saturday', fillColor:'ff00bf', stroke:false, strokeColor:'ffffff', strokeWidth:0}, 
	        sun:{lang:'Sunday', fillColor:'000000', stroke:false, strokeColor:'ffffff', strokeWidth:0}, 
	        multidays:{lang:'Multiple', fillColor:'ffffff', stroke:true, strokeColor:'ff0000', strokeWidth:2}
        }
        var place_id="xx",  //id in DB
		place="place-available-"+place_id,  // key element of the map
		day_arr=$j("#available_day").chosen().val(),  //selected days
		opts_tooltip="<b style=\"color:#ff0000\">some_place_code</b> - the_place_desc<br>",
		day_elem='', //options of the selected day
		day_current, color_day, lang_day,
		days_tooltip=[],
		place_options=new Object();
	map_available.mapster("set", false, place); //if this line is commented, fillColor won't change
	if(day_arr.length==1){
		opts_tooltip+="Available for day: ";
		day_elem=day_arr[0];
	}
	if(day_arr.length>1){
		opts_tooltip+="Available for days:<br>";
		day_elem="multidays";
	}
        place_options.fillColor=days[day_elem]["fillColor"];
        place_options.stroke=days[day_elem]["stroke"];
        place_options.strokeColor=days[day_elem]["strokeColor"];
        place_options.strokeWidth=days[day_elem]["strokeWidth"];
	for(i=0;i<day_arr.length;i++){
		day_current=days[day_arr[i]];
		color_day=day_current.fillColor;
		lang_day=day_current.lang;
		days_tooltip[i]="<b style=\"color:#"+color_day+"\">"+lang_day+"</b>";
	}
	opts_tooltip+=days_tooltip.join("<br>");
	place_options.toolTip=opts_tooltip;
	map_available.mapster("set", true, place, place_options);
```

This code updates almost everything, except for the tooltip.

Only works when I use "set_options". This is the additional code

```
place_options.key=place;
var options=map_available.mapster("get_options"), areas_opts=options.areas;
areas_opts.forEach(function(item, index){
    if(item.key==place){
        options.areas[index]=place_options;
    }
});
map_available.mapster("set_options", options);

```

Is there another way to update the "tooltip" of an area without setting all the options for the map?

Thanks in advance and my apologies for my poor English

**Comment by techfg** [comment]
Hello @rcaguirreg -

As currently designed, the `set` API will not modify/adjust any options that are not related to rendering, toolTip amongst those.  This is why the toolTip isn't changing after you call set and pass in a new toolTip value.

When calling set_options, you do not need to provide all the options, only the ones you want to change.  IM will merge the existing options with those that are passed.  Depending in your use case, this might simplifying things for you since you might be able to call set_options with only the toolTip specified.

That said, IM v1.4 introduced many new fixes/features related to toolTips including the ability to specify a function for a toolTip.  In your case, using a function is likely your best path as your function could just generically locate the tooltip via a data attribute (or something similar).  For more information on v1.4, please see:

1) [ToolTip Example](https://github.com/jamietre/ImageMapster/blob/master/examples/tooltips.html)
2) [v1.4.0 ChangeLog](https://github.com/jamietre/ImageMapster/blob/master/CHANGELOG.md#version-140---20210124)
3) [Basic ToolTip example](https://jsfiddle.net/techfg/gnqdo0mp/2/)

I'm going to go ahead and close this issue.  If you have any further general questions on IM usage, as mentioned in our [Contributing Page](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md) and in our issue template, please use one of the options described in our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.  If you'd like to report a bug, please open a new issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines and if you'd like to request a feature, please open a new issue following our [Feature Request](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.
