### ISSUE TITLE
Safari's OCR/Live Text is blocking image zones

### ISSUE THREAD

**Issue by jarodljohnson** [jamietre/ImageMapster#393]
**Describe the bug**
Safari 15's Live Text feature is adding shadow content to images with text.  The shadow content is appearing on top of the image so that users can select and copy the text, but it's blocking the image zones so they're not clickable or highlightable.

**To Reproduce**

1. Go to https://jsfiddle.net/jLsdkhze/4/
2. Wait for 15 - 30 seconds
3. Try to click on any of the words

**Expected behavior**
Hovering over the words should activate a tooltip and add a border around the word (the zones in this example aren't exactly lined up  with the words, but that doesn't affect the behavior).  Clicking on a word should add a border that stays visible until it is unselected.  This works for a little while, but eventually Safari adds that shadow content and the items are no longer highlightable or clickable.

**Screenshots**
![image](https://user-images.githubusercontent.com/26629681/153435043-b8c7bd98-1494-481a-8a4b-ef88e25ff53f.png)

**Desktop (please complete the following information):**
- OS: Monterey
- Browser Safari
- Version 15

**Smartphone (please complete the following information):**
- Device: iPhone13
- Browser Safari
- Version 15

**Additional context**
I've found with this example, the Live Text is sort of hit or miss.  Sometimes it shows up, sometimes it doesn't.  Selecting the image or double clicking it like you're trying to copy the text seems to help trigger the Live Text, but not always.  You can also right click on the image and inspect the element, and see the shadow content appear there.

**Comment by techfg** [comment]
Hello @jarodljohnson -

Thank you for reporting this.  In doing some research, there are other reports of `Live Text` causing issues with `imagemaps` (and other `img` based scenarios) so this does not appear to be an issue with `imagemapster` itself, but rather an issue with `Live Text` and it interfering with `imagemaps` in general.

[Here is a repro](https://jsfiddle.net/techfg/rkw45pgz/3/) of an `imagemap` without `imagemapster` and it exhibits the same issue as your repro when `Live Text` is enabled on the system.

In an effort to try to find a solution, I was hopeful that there is a way to "disable" `Live Text` for a particular image on a webpage but I was unable to find a way to do this outside of turning off `Live Text` on the entire system.  There is mention of being able to use the html attribute  `x-apple-data-detectors="false"` ([here](https://stackoverflow.com/questions/2106102/disabling-data-detectors-for-a-specific-html-element-in-a-uiwebview)) and/or setting css `webkit-user-select: none; user-select: none;` ([here](https://stackoverflow.com/a/77997028)) but neither seemed to work as I believe they both may be specific to `anchor` elements (I'm far from an Apple expert).

Fortunately, I was able to come up with a solution based on information found in the following:

1. https://stackoverflow.com/questions/70779449/html-image-map-stops-working-on-ios-safari
1. https://forums.developer.apple.com/forums/thread/709384

In short, `imagemapster` takes the original image and makes a copy of it and then adds canvas elements for drawing, however it leaves the original image in-place with an opacity of 0.  `Live Text` is grabbing a hold of the original image and attaching to it so based on some testing, the key is avoiding having `Live Text` find any text so that it just "moves on" so to speak.  We can accomplish this by changing the `src` attribute of the original image after `imagemapster` has completed its initialization.

```js
  onConfigured: () => {
    // Replace the original source with a 1x1 transparent image
    $img.attr('src', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=');
    // Replace the css attributes to ensure we take up full container height/width
    // and are "visible" so Live Text doesn't look "through" the image
    $img.css({
      height: '100%',
      width: '100%',
      opacity: 0.01
    });
  }
```

Link to full sample: [ImageMapster Live Text Workaround](https://jsfiddle.net/techfg/jtxzhywp/5/)

Given this is a workaround and the root issue isn't really an `ImageMapster` issue directly, I'm hesitant to officially add this as a feature to ImageMapster, at least not without a lot more testing and evaluation of other potential approaches but I'm hopeful that this may help you and/or anyone else that is encountering this issue.

All that said, since it's been a while since you posted this issue, I'm curious if you were ever able to come up with a solution?

Thanks!

**Comment by techfg** [comment]
Thanks for circling back @jarodljohnson.  Makes sense about Image Map Pro not having issues with Live Text as they take a different approach for "hot" areas so there are "blocking" elements on top of the image itself that prohibits Live Text from reading the image text itself.

One thing I didn't mention in previous post is that if `unbind` is called, the original source image would need to be put back so that the transparent image doesn't remain.  A sample of how to do this is [here](https://jsfiddle.net/techfg/72swxkeo/1/).

I'm going to close out this issue but if you do end up revisiting any of this in the future, would appreciate you sharing your results/findings.
