### ISSUE TITLE
Tooltip is inconsistent, it shows up on most areas but does not on couple of area item.

### ISSUE THREAD

**Issue by rvasudev-ipa** [jamietre/ImageMapster#403]
I am using the library to display tooltip on some rectangle only areas on a image map on my WordPress custom theme. Using tooltip to expand on few technical terms on a data graph.

The tooltip displays well for most of the terms but it does not on couple of them, even though the values are all correct and have correctly loaded as area elements with right coordinates. The area is highlighted too with the given fill color when hovered over but somehow the tooltip still does not show up but most of the other terms works just fine.

I have attached screenshots of tooltip working just fine for other terms but not working for particular terms even though it is being highlighted.
![area-element-loaded](https://github.com/jamietre/ImageMapster/assets/151782375/54eba20f-adbb-4c01-b5d8-bf33fb2c75ce)
![area-highlighted-tooltip-not-showing](https://github.com/jamietre/ImageMapster/assets/151782375/2de8d516-f52a-4c2c-be75-85f3f9f28818)
![tooltip-showing](https://github.com/jamietre/ImageMapster/assets/151782375/004cd212-8156-40f3-8dd7-a5874d5e01b8)

Any help is appreciated, thanks!

**Comment by techfg** [comment]
Hello @rvasudev-ipa -

Sorry to hear your encountering an issue with the tooltips.  Unfortunately, your bug report does not provide enough information to reproduce the issue.  Please provide a full repro of the issue using [jsfiddle](https://jsfiddle.net) (or similar) so that we can investigate further.

Thank you!

**Comment by techfg** [comment]
Hello @rvasudev-ipa -

Thank you for providing the repro, was able to reproduce the issue and identify the source of your issues.

1. Trailing spaces in map area keys - Three of your areas have a trailing space in the `data-key` which results in IM not being able to identify the options for those areas.  When IM initializes, it inspects all areas in the associated map (from `usemap`) and then takes the options passed and associates those options to the areas identified in the actual HTML.  When doing so, it [removes leading & trailing whitespace from the keys](https://github.com/jamietre/ImageMapster/blob/05db123794aef6ffdb709d021d9171095dd7e920/src/areadata.js#L362) so the options you passed in do not match the keys that it found in the html.  Simply removing the trailing whitespace in your HTML `data-key` attribute solves this issue.  For example:

```diff
- data-key="BUILDING PROJECT WORK PROCESS AND GOVERNANCE "
+ data-key="BUILDING PROJECT WORK PROCESS AND GOVERNANCE"
```

2. Keys contain commas - Per the [docs](http://www.outsharked.com/imagemapster/default.aspx?docs.html), IM supports map groups which are defined in the `mapKey` with each member of the groups `key` separated by a comma.  In your case, I believe the area `CUSTOMIZED LARGE, COMPLEX PROJECT WORKSHOPS` is not intended to be a group but rather an individual area, however it contains a comma in the key so IM treats this as a group of `CUSTOMIZED LARGE` & `COMPLEX PROJECT WORKSHOPS`.  Removing the comma from the key solves this issue.  For example:

```diff
- data-key="CUSTOMIZED LARGE, COMPLEX PROJECT WORKSHOPS "
+ data-key="CUSTOMIZED LARGE COMPLEX PROJECT WORKSHOPS"
```

Making the above changes alone (3 changes in total - 2 trailing whitespace & 1 comma) should resolve all your issues - here is a [jsFiddle](https://jsfiddle.net/techfg/fyhjsnux/) with only the changes above applied.  

That said, if I'm understanding what you are trying to accomplish with IM correctly, you can greatly simplify your IM configuration and also adhere to its intended usage approach.

1.  Areas - You are building area specific options but they are the same for every area so there is no need to build area specific options and you can use default options for all areas.  The purpose of area options is to have different functionality for one (or more) areas and only in those situations do you need to specify the area options.  In fact, you could have 100 areas in your map and only specify area options for one to differentiate that one from the defaults.  As mentioned above, when IM initializes, it parses the HTML for all `area` elements in the `map` element and will use all of them with defaults unless overridden by options in the `areas` configuration property.

1. Tooltips - You are setting `toolTip` in area options to `true` - the `toolTip` property is intended to be the content of the tooltip itself, not a boolean to indicate that a tooltip should be displayed so while you won't see the result because of your `onShowToolTip` code, a toolTip is displayed with the text content of `true` initially and then you change that content in `onShowToolTip`.  While `onShowToolTip` can be used to modify the tooltip content (which you are currently doing), it fires after the tooltip is displayed and its intended use is when you need to do something after a tooltip is displayed (not to construct the tooltip itself).  For your scenario, you can move the logic in `onShowToolTip` to the `toolTip` property.

1. `onMouseOver` & `onMouseOut` events - It appears you are using this to control the `fillColor` of the area when it's highlighted, although you are actually `selecting` the area.  Unless you have code/logic elsewhere that relies on `selected`, you can simply set `fillColor` option on default configuration (you already have this) and use the default values of `toolTipClose` which includes `onMouseOut` and it will use that for highlighting.  You could also use `render_select` and/or `render_highlight` configuration options if you want to have a different `fillcolor` when highlighted vs. selected.

1. There is a dangling `p` tag within your areas - While this doesn't hurt anything, it can simply be removed as I don't believe it serves any purpose in your scenario.

1. Maps Keys - While you can use anything for map keys, I'd recommend converting to using some type of `unique id` (e.g., a `record_id` from a database, etc.) to avoid issues like you are encountering with whitespace & commas.

1. Href value of `#!` - Its not clear to me why you have a `!` in your href values.  If you do not intend for an href to be followed when an area is clicked, you should have `#` as IM uses this as a "special identifier` to skip navigation.  You could also simply set `clickToNavigate` to `false` which is the default value for this option.

Here is a [jsFiddle](https://jsfiddle.net/techfg/cvofydmx/1/) that incorporates all of the recommended changes.

Please let us know if the above information resolves your issue.

**Comment by rvasudev-ipa** [comment]
Hi @techfg 

Thank you for the solution! This worked, really appreciate it! However, I came across another issue where the image is not responsive in mobile along with its coordinates showing wrong. It works fine until 800px screen width and then the image is cut off and the coordinates appear to be wrong in mobile. Could you please let me know what is the problem here, I thought the image would be automatically become responsive once I initialize the image with mapster function? Thanks for your help in advance!

**Comment by techfg** [comment]
Hello @rvasudev-ipa -

Glad it worked!  Autoresize was added in [v1.5.0](https://github.com/jamietre/ImageMapster/blob/main/CHANGELOG.md#version-150---20210129), however you do not have it enabled.  Please see #359 and the example [here](https://github.com/jamietre/ImageMapster/blob/main/examples/autoresize.html).
