### ISSUE TITLE
[✨] Allow areas with no href or href empty without user feedback on the status bar

### ISSUE THREAD

**Issue by dec** [jamietre/ImageMapster#423]
### Is your feature request related to a problem and/or adding functionality? Please describe

Hello there,

First of all, thanks very much for your work on this project, it's really useful. I have a "problem" related with the "href" attribute of the area elements. I am not sure if this is solved in some way, I try various possible ways, but without lucky.

The problem is the feedback that the browsers place in the status bar when hover the mouse on an area with the "href" attribute. My intention to use ImageMapster is to prepare a kind of "test" with the image map.

The idea is that the user will be asked with a question like: "Please, select the correct items in the image". The problem with this scenario is that, when an user hover the mouse over an area, the browser show the URL (even if "href" is empty) in the status bar, so, in some way, the user will know where the items are...

I try by removing the "href" attribute, or by use the "nohref" attribute. I play a bit with this and the "mask" options of ImageMapster, but, I can't get the desired result. Basically I want that a "nohref" or "href" empty area continue to work "as a normal area", basically react when press on it, but, avoiding the feedback / hint in the status bar that the browsers shown.

Can anyone help me on this? 

I hope you understand what I am trying to explain: please, if you have any questions, don't hesitate to post it here and I will try to reply it as quickly as possible. Thanks very much in advance for any help!

### Describe the solution you'd like

The solution that I'd like to have is that areas with empty "href" attributes, or with some kind of attribute / value, works like other areas: the whole idea is to avoid the feedback / hint that the browsers place in the status bar, which in some way "tell the user" where an area is located, something totally wrong for our specific project.

### Describe alternatives you've considered

I try a possible workaround, by placing a link (HTML A tag) for the image map itself, so, we can see the URL in the status bar always, and this may help with the desired result: the user don't know if there is an area over the mouse cursor, because the status bar URL is always shown, not only when reach an area.

However, this workaround have some caveats, for example, we can certainly catch the image map link, however, the user can use the middle button of the mouse, for example, in order to open the link in a new browser tab, and, this will ends in a non desired behavior.

### Additional context

No additional context.

**Comment by dec** [comment]
Hello to all,

Just to add some information. Other thing I do is to handle the "auxclick" event of the "fake link" which I use for the entire image map, and, apparently, I can't handle the mouse middle button. However, I am not sure if this can work in all browsers.

**Comment by techfg** [comment]
Hello @dec -

Thanks for the feature request.  Although I'm not 100% clear on what you're trying to achieve, I think I understand enough of it to get the basic idea.  The main thing I do not understand, sorry, is that the browser shows the URL in the status bar, however if you have a `href="#"` value, it should show the URL of the current page so I'm not clear on why the current page URL "gives the user the answer" for your specific project.  If you can provide more details on this that would be ideal.

Regarding the feature, ImageMapster is currently written to treat anything with `nohref` or `#` in the href as a "no-op", meaning its ignored.  Masks with these values can be treated a little different but I don't think masks is the solution for your situation if I'm understanding it properly.  Changing how ImageMapster works as it relates to this could be a pretty significant change unlikely to be done unfortunately since ImageMapster really isn't actively developed anymore.

With that said, here are a couple of ideas if I'm understanding your request:

1. Use `javascript:void(0)` or any other value for the href (e.g., `href="javascript:void(0)"` or `href="https://somefakeurl.com"`.  If you need "click" behavior, you can use the various options in ImageMapster to control what happens when a user clicks on an area (e.g., [clickNavigate](https://jamietre.github.io/ImageMapster/reference/configuration-reference/#clicknavigate), [navigateMode](https://jamietre.github.io/ImageMapster/reference/configuration-reference/#navigatemode), [onClick](https://jamietre.github.io/ImageMapster/reference/configuration-reference/#onclick), etc.).   Here is an [example](https://jsfiddle.net/techfg/7pnchwme/).
2. If the above doesn't work, you can try removing the `href` values AFTER imagemapster has completed its initialization.  By removing the `href`, the browser won't show anything.  Once you do this, some of the ImageMapster functionality will still work (e.g., clicks will still work), however other things won't (e.g., mouseover events).  For those that you need that don't work, you can use the ImageMapster API to trigger them yourself.  Here is an [example](https://jsfiddle.net/techfg/e7znks8p/) that strips the `href` in the `onConfigured` event and then handles `mouseover` to highlight areas.

Hopefully one of these will help your situation.  If not, please provide more details and specifics on what you are looking for and ideally, a [jsFiddle](https://jsfiddle.net) sample with step-by-step information on what the user experience should be at each step of the process.

Hope this helps!

**Comment by dec** [comment]
Hello @techfg,

First of all, thanks very, very much for your help. And, please, sorry for the delay: or I am totally wrong (and I delete the EMail notification), or I did not get notified about your post, even when I am subscribed to this topic.

Sorry for the misunderstanding: it's without doubts caused by my not very well English. The whole point here is that we are using ImageMapster to present to the user a "test". Basically we ask the user, "Please, select the dangerous elements that you can see in the image".

Then the image will contains several elements, some of them are the dangerous elements that the user must press / select, and, others are "fakes", to confuse the user, to say like that, since we are doing a test to the user.

The point is that if the user see in the browser status bar "an URL" while the mouse is over certain area, a wise user can understand that there is the "dangerous" element that we expect to be pressed, since the "not defined areas" of the image did not present that "URL" in the browser status bar.

I hope you understand what I am trying to explain, but, if not, please, don't hesitate to ask me and I will try to explain it as best as possibe.

On the other hand, thank to your help, the problem is solved!! From your two proposed approaches, the number one cannot be used, since even if we place "javascript:void(0)" in the "href" attribute, the browser still show it in the status bar.

However, your second proposed approach  is exactly the solution, at least in our specific case. Certainly, what I do is follow your approach: I use the "onConfigured" event to remove the "href" attribute of the defined areas. And this works like a charm, that is, certainly must be taken with caution, since may something will not work as expected, but, in our specific case, this completely solve the problem, since there is no more "hints" in the browser status bar.

So, again, thanks very much for your help, since what I do to "solve" the problem is to wrap the image map with a link, therefore, the browser show the "URL / hint" in browser status bar, but, for the entire image, no matter if the mouse is over an area or not. This works, more or less, but, the perfect solution is the one proposed by you, sir.

On the other hand, it's a pain that this project is no more in development! I reach this project looking for a responsive image map, and, it's the only project that we see good to be used, not only for this specific responsive feature, but, also for many others, and, apart of the good documentation.

We, in particular, cannot use SVG, which maybe it's the other possible way to get something like an "image map" with responsive capabilities. So, I reach your project, and, or I am totally wrong, or, it's unique in their specie, so, it's a real pain to hear that it's no more in development, since, that's is one of the reasons that we consider to use the project, in addition to all what I say: we really appreciated that a library that we will use is widely used and well supported and documented.

I don't know what to say... I may want to ask if you know about some possible alternative... but... in fact I already start with this project and want to continue using it!

Anyway, you may have your reasons, and, we are nobody to say anything: except what I already say, of course.

Thanks very, very much again for this project and your help, sir!

**Comment by techfg** [comment]
Hello @dec -

Glad to hear it worked for you!  Regarding the project, ImageMapster is stable and contains a large majority of the features that users have asked for so there really isn't a need to dedicate the time to actively develop it.  It does receive updates from time to time, for example, the current website was just launched a few months ago so the project is not dead by any means, just not actively developed :)

Regarding alternatives, I haven't found any that offer the existing set of features although that doesn't mean they don't exist.  I use ImageMapster myself on projects, that's how I got started as a contributor to the project.

I think you're safe to use ImageMapster for your project if it suits your needs.  If you have any additional feature requests or identify any bugs, please do create issues like you did and they will be considered, just can't guarantee they will be added/addressed (although at minimum if it's a bug it likely would be).

Good luck with your project!

**Comment by dec** [comment]
Hello @techfg!

Thanks for your reply. Your words are really enough, I mean, understanding that the project already offers a lot of features and it's quite stable, certainly may no need a daily development. However, if a project's developer is open to fix possible bugs, is open to possible contributions, etc., it's in fact developing the project!

So thanks very much again, sir, and, thanks very much again for your work on ImageMapster!
