### ISSUE TITLE
"target" attribute on areas not working with clickNavigate

### ISSUE THREAD

**Issue by jamietre** [jamietre/ImageMapster#70]
Without ImageMapster, you can use `target="_blank"` to open a new window. ImageMapster interevenes and uses javascript to navigate. We need to simulate `target` options when navigating.

**Comment by coolgrafix** [comment]
Coming to this conversation late. It's very important to note that linking with the onClick event won't work if the clickNavigate property is set to true; I assume that's why it defaults to false. In the original post above, the poster has it set to true, so I assume this is the mysterious reason it wasn't working. Had the same trouble on my end, and I don't think this was documented at the Docs pages for the onClick handler or clickNavigate property. Hope this helps someone, because this was quite perplexing on my end.

**Comment by kimdaley** [comment]
I am very new to jquery. I am using imagemapster to create an interactive map. I've set it all up and it is working in Chrome and Safari as well as my mobile browser. I haven't tried it on ie yet. I can't seem to get the map to work in Firefox. When looking in the console, it appears that it has something to do with the way I am calling image.mapster from my external js file. Any suggestions would be great! the page is here:
www.myusara.com/sample-map/

**Comment by pathana** [comment]
@NKarasek Thank you Nick this works great!!

**Comment by techfg** [comment]
Full support for href & target handling has been added in #354
