### ISSUE TITLE
Feature: If singleSelect is true and listSelectedClass is not null, remove listSelectedClass from all other items in boundList

### ISSUE THREAD

**Issue by mikemccaughan** [jamietre/ImageMapster#83]
I'm using ImageMapster's functionality for syncing with an external list, and it works like a charm, except that even if I have `singleSelect: true` in the options, I still see mutiple items in my external list as "selected". I do have a simple workaround:

```
onClick: function (data) {
    data.listItem.siblings().removeClass(listSelectedClass); // replace listSelectedClass with actual class name
}
```

However, it would be nice if this were handled automatically. I expect the same thing applies to `listSelectedAttribute`.

**Comment by MG7282** [comment]
what's data supposed to be? I'm receiving TypeError: data.listItem is undefined

**Comment by techfg** [comment]
Hello @mikemccaughan -

Thank you for reporting this and apologies for the delayed reply!

I have confirmed this to be a bug and upon researching have identified several different issues all of which occur regardless of whether or not the user clicks on an area or the corresponding API is involved (`set`/`select`/`deselect`):

**Describe the bug**
1. when `singleSelect === true` & item deselected, listSelectedClass is not removed
2. when `singleSelect === true` & item deselected, listSelectedAttribute is not removed
3. on initialization, listSelectedClass & listSelectedAttribute are not applied according to selected state of area.  As an example, if an area has `selected === true`.
4. when `unbind` & `init` list is not synced
5. when `rebind` list is not synced

**To Reproduce**
Steps to reproduce the behavior:

1. Go to [jsFiddle](http://jsfiddle.net/techfg/mfk4uxde/119/)
2. `Red Pepper` is marked `selected` in area config but listSelectedAttribute & Class are not applied to bound list
3. Click on `carrots` - list updates with listSelectedClass (resulting in blue background) and listSelectedAttribute (resulting in white text)
4. Click on `celery` - list updates for celery but carrots is not removed
5.  Click `Reset Map` - carrots is not removed and red pepper is not updated
6. Click on 'Rebind Map` - squash was added as a configured area with `selected === true` and it is selected but list is not updated.  Note that singleSelect is not respected here which is a separate issue covered in #370.

**Expected behavior**
IM should sync listSelectedClass & listSelectedAttribute on every `selected` change that occurs either via user action or API call.
