### ISSUE TITLE
Area specific highlight effect with alt image

### ISSUE THREAD

**Issue by aduke** [jamietre/ImageMapster#90]
I am trying to build 1 map that has some areas that use an alt image as the highlight effect and other areas that use fill colors as the highlight effect. Is this possible?

Can I specify an alt image and then override the area highlight  part for some areas so that it just uses fillColor?... 

or only specify altImage for certain areas?

**Comment by ApetweBc** [comment]
Guys using altImage produce. It seems the image is not loaded before initiates. How do I solve this?
 ```
to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLImageElement or SVGImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap or OffscreenCanvas)
```

**Comment by techfg** [comment]
@ApetweBc - The issue you are encountering is likely the same as the one identified in #316.  Please see details there and try using the latest version of IM where that issue was addressed.  Also, for future reference, please open new tickets when reporting issues rather than commenting on closed tickets as we're unlikely to see anything added to closed issues.
