### ISSUE TITLE
Wordpress Themes

### ISSUE THREAD

**Issue by steve-eldridge** [jamietre/ImageMapster#93]
This is a great tool and I've spent the weekend exploring it. However I can't find the issue that is preventing it from working in Wordpress.

I've tried blank themes, turning off virtually everything possible I can't find a debugging issue that would prevent it from working.

I would be happy to work with you to find a solution, I think this tool is very powerful and I would like to find a way to get this to work.

**Comment by techfg** [comment]
@steve-eldridge -

Apologies for the delayed reply on this!

Unfortunately, there isn't much to go on from your messages other than "its not working in WP" but I can't find any information that describes what is not working.  You indicate there are no error messages, etc. but functionality wise its unclear what wasn't working.

One common oversight that I've seen people make it not specifying an `href` attribute on the area.  As described in the docs, the absence of an `href` attribute (or specifying `nohref`) will essentially disable all mapster functionality (e.g. highlighting, selecting, etc.).  Unless you do not want IM to trigger functionality for a particular area, always specify an href of at least `#` (e.g., `href='#'`).

Outside of that thought and without any further details on what wasn't working, its difficult to say what the issue was given others were using WP successfully.

If this is still an issue you for, please update this ticket per our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines (e.g. full repro, description of expected/actual behavior, etc.) and we'd be happy to try to help.

**Comment by techfg** [comment]
Hello @steve-eldridge -

It has been over 30 days since we last heard from you so we are going to close this issue.

If you need further assistance, please choose one of the following options:

1. For general IM questions, how to's, usage, etc., please use one of the options described on our [Support](https://github.com/jamietre/ImageMapster/blob/master/SUPPORT.md) page.
2. If you believe you have identified a bug in IM, please update this issue following our [Bug Reports](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#bug-reports) guidelines.
3. If you would like to request a new feature for IM, please open a new issue following our [Feature Requests](https://github.com/jamietre/ImageMapster/blob/master/CONTRIBUTING.md#feature-requests) guidelines.
